/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

exports.seed = async function (knex) {
  await knex("detailed_reviews").del();

  await knex("detailed_reviews").insert([
    {
      match_id: 1,
      player_id: 1, // Courtois
      minutes_played: 90,
      goals: 0,
      assists: 0,
      saves: 5,
      tackles: 0,
      interceptions: 0,
      chances_created: 0,
      coach_rating: 8,
      shots_on_target: 0,
      shots_off_target: 0,
      passes_completed: 32,
      passes_attempted: 40,
      dribble_duels_won: 0,
      dribble_duels_lost: 0,
      defensive_duels_won: 1,
      defensive_duels_lost: 0,
      fouls_committed: 0,
      fouls_suffered: 0,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 0,
      clearances: 1,
      aerial_duels_won: 0,
      aerial_duels_lost: 0,
    },
    {
      match_id: 1,
      player_id: 2, // Trent Alexander-Arnold
      minutes_played: 90,
      goals: 0,
      assists: 1,
      saves: 0,
      tackles: 3,
      interceptions: 2,
      chances_created: 3,
      coach_rating: 7,
      shots_on_target: 1,
      shots_off_target: 0,
      passes_completed: 65,
      passes_attempted: 72,
      dribble_duels_won: 2,
      dribble_duels_lost: 1,
      defensive_duels_won: 3,
      defensive_duels_lost: 2,
      fouls_committed: 1,
      fouls_suffered: 1,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 0,
      clearances: 2,
      aerial_duels_won: 1,
      aerial_duels_lost: 0,
    },
    {
      match_id: 1,
      player_id: 3, // Virgil van Dijk
      minutes_played: 90,
      goals: 0,
      assists: 0,
      saves: 0,
      tackles: 4,
      interceptions: 3,
      chances_created: 0,
      coach_rating: 8,
      shots_on_target: 0,
      shots_off_target: 1,
      passes_completed: 58,
      passes_attempted: 63,
      dribble_duels_won: 1,
      dribble_duels_lost: 0,
      defensive_duels_won: 6,
      defensive_duels_lost: 1,
      fouls_committed: 1,
      fouls_suffered: 0,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 0,
      clearances: 6,
      aerial_duels_won: 4,
      aerial_duels_lost: 1,
    },
    {
      match_id: 1,
      player_id: 4, // Jules Koundé
      minutes_played: 90,
      goals: 0,
      assists: 0,
      saves: 0,
      tackles: 3,
      interceptions: 2,
      chances_created: 1,
      coach_rating: 7,
      shots_on_target: 0,
      shots_off_target: 0,
      passes_completed: 52,
      passes_attempted: 59,
      dribble_duels_won: 1,
      dribble_duels_lost: 1,
      defensive_duels_won: 4,
      defensive_duels_lost: 2,
      fouls_committed: 2,
      fouls_suffered: 1,
      yellow_cards: 1,
      red_cards: 0,
      offsides: 0,
      clearances: 3,
      aerial_duels_won: 2,
      aerial_duels_lost: 1,
    },
    {
      match_id: 1,
      player_id: 5, // Andrew Robertson
      minutes_played: 90,
      goals: 0,
      assists: 1,
      saves: 0,
      tackles: 2,
      interceptions: 1,
      chances_created: 2,
      coach_rating: 7,
      shots_on_target: 1,
      shots_off_target: 1,
      passes_completed: 50,
      passes_attempted: 58,
      dribble_duels_won: 3,
      dribble_duels_lost: 1,
      defensive_duels_won: 3,
      defensive_duels_lost: 1,
      fouls_committed: 1,
      fouls_suffered: 2,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 0,
      clearances: 2,
      aerial_duels_won: 1,
      aerial_duels_lost: 0,
    },
    {
      match_id: 1,
      player_id: 6, // Luka Modric
      minutes_played: 90,
      goals: 0,
      assists: 2,
      saves: 0,
      tackles: 3,
      interceptions: 2,
      chances_created: 4,
      coach_rating: 9,
      shots_on_target: 1,
      shots_off_target: 0,
      passes_completed: 85,
      passes_attempted: 90,
      dribble_duels_won: 4,
      dribble_duels_lost: 1,
      defensive_duels_won: 2,
      defensive_duels_lost: 1,
      fouls_committed: 1,
      fouls_suffered: 3,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 0,
      clearances: 0,
      aerial_duels_won: 1,
      aerial_duels_lost: 0,
    },
    {
      match_id: 1,
      player_id: 7, // Kevin De Bruyne
      minutes_played: 90,
      goals: 1,
      assists: 1,
      saves: 0,
      tackles: 1,
      interceptions: 1,
      chances_created: 5,
      coach_rating: 9,
      shots_on_target: 2,
      shots_off_target: 1,
      passes_completed: 75,
      passes_attempted: 83,
      dribble_duels_won: 3,
      dribble_duels_lost: 2,
      defensive_duels_won: 1,
      defensive_duels_lost: 1,
      fouls_committed: 0,
      fouls_suffered: 2,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 1,
      clearances: 0,
      aerial_duels_won: 1,
      aerial_duels_lost: 1,
    },
    {
      match_id: 1,
      player_id: 8, // Jude Bellingham
      minutes_played: 90,
      goals: 1,
      assists: 0,
      saves: 0,
      tackles: 2,
      interceptions: 2,
      chances_created: 3,
      coach_rating: 8,
      shots_on_target: 3,
      shots_off_target: 1,
      passes_completed: 70,
      passes_attempted: 76,
      dribble_duels_won: 4,
      dribble_duels_lost: 2,
      defensive_duels_won: 2,
      defensive_duels_lost: 1,
      fouls_committed: 1,
      fouls_suffered: 2,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 0,
      clearances: 1,
      aerial_duels_won: 2,
      aerial_duels_lost: 1,
    },
    {
      match_id: 1,
      player_id: 9, // Kylian Mbappe
      minutes_played: 90,
      goals: 2,
      assists: 0,
      saves: 0,
      tackles: 1,
      interceptions: 0,
      chances_created: 3,
      coach_rating: 9,
      shots_on_target: 4,
      shots_off_target: 2,
      passes_completed: 48,
      passes_attempted: 55,
      dribble_duels_won: 6,
      dribble_duels_lost: 3,
      defensive_duels_won: 1,
      defensive_duels_lost: 2,
      fouls_committed: 2,
      fouls_suffered: 3,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 2,
      clearances: 0,
      aerial_duels_won: 0,
      aerial_duels_lost: 1,
    },
    {
      match_id: 1,
      player_id: 10, // Leo Messi
      minutes_played: 90,
      goals: 1,
      assists: 2,
      saves: 0,
      tackles: 0,
      interceptions: 0,
      chances_created: 5,
      coach_rating: 9,
      shots_on_target: 3,
      shots_off_target: 1,
      passes_completed: 60,
      passes_attempted: 66,
      dribble_duels_won: 7,
      dribble_duels_lost: 2,
      defensive_duels_won: 0,
      defensive_duels_lost: 1,
      fouls_committed: 0,
      fouls_suffered: 4,
      yellow_cards: 0,
      red_cards: 0,
      offsides: 1,
      clearances: 0,
      aerial_duels_won: 0,
      aerial_duels_lost: 0,
    },
    {
      match_id: 1,
      player_id: 11, // Erling Haaland
      minutes_played: 90,
      goals: 2,
      assists: 0,
      saves: 0,
      tackles: 1,
      interceptions: 1,
      chances_created: 2,
      coach_rating: 8,
      shots_on_target: 5,
      shots_off_target: 1,
      passes_completed: 42,
      passes_attempted: 49,
      dribble_duels_won: 3,
      dribble_duels_lost: 1,
      defensive_duels_won: 2,
      defensive_duels_lost: 1,
      fouls_committed: 1,
      fouls_suffered: 2,
      yellow_cards: 1,
      red_cards: 0,
      offsides: 2,
      clearances: 0,
      aerial_duels_won: 3,
      aerial_duels_lost: 1,
    },
  ]);
};
